# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
